name: "测试用例缺失"
description: "报告测试用例缺失"
title: "[Lack of TestCase] "
labels: ["Lack of TestCase / 测试用例缺失"]

body:
- type: markdown
  attributes:
    value: 欢迎为 mugen-riscv 提出新的 Issue！烦请填写以下表单：
- type: checkboxes
  id: confirm
  attributes:
    label: 请选择：
    options:
    - label: 我已经检查了 [Issue](https://github.com/brsf11/mugen-riscv/issues)，进行了搜索，但没有发现类似问题
      required: true
    - label: 我正在着手修复该问题
      required: false
    - label: 我希望接手该问题
      required: false
- type: input
  id: testcaseURL
  attributes:
    label: 测试用例路径
    description: 如果添加这个用例，该测试用例路径及文件名应该是
    placeholder: "e.g. testcases\\cli-test\\abrt\\oe_test_service_abrtd.sh"
  validations:
    required: true
- type: input
  id: packagename
  attributes:
    label: 包名
    description: 请填写包名，如果这个软件包的所有测试套均未测试，则下列框无需填写。
    placeholder: "e.g. watchdog"
  validations:
    required: true
- type: input
  id: testsuitname
  attributes:
    label: 测试套名称
    description: 请填写测试套名称
    placeholder: "e.g. cli-test"
  validations:
    required: false
- type: input
  id: testcasename
  attributes:
    label: 测试用例名称
    description: 测试用例名称
    placeholder: "e.g. watchdog"
  validations:
    required: false
- type: textarea
  id: needs
  attributes:
    label: 测试用例功能
    description: 请简要介绍该测试用例的功能或测试目的
  validations:
    required: true
- type: textarea
  id: introduction
  attributes:
    label: 测试用例简要描述
    description: 请简要介绍该测试用例的运作过程（如果你有思路）
  validations:
    required: false
- type: dropdown
  id: version
  attributes:
    label: 该测试用例运行的环境
    description: 请在下列选项中选择一个适当的选项以描述该测试用例运行的环境
    options:
      - 仅 openEuler-riscv 需要
      - openEuler-riscv 和 x86-64 均需要
      - 不确定
      - 以上选项均不正确（我将在其他信息处报告相关内容）
  validations:
    required: true
- type: textarea
  id: othors
  attributes:
    label: 其他有助于解决该问题的内容
    description: 如果你了解相关的其他信息，请在此处报告